quiet socat

diff --git a/compose.yml b/compose.yml
--- a/compose.yml
+++ b/compose.yml
@@ -1,5 +1,6 @@
 services:
-  geant4: # docker compose --profile geant4 up or docker compose run --rm geant4 tmux -u
+  geant4:
+    # docker compose --profile geant4 up or docker compose run --rm geant4 tmux -u
     image: physino/geant4:latest # minimalistic container image + cmd-line tools
     platform: linux/amd64 # for run time
     profiles: [ "geant4" ]
@@ -8,10 +9,12 @@ services:
     # feel free to change the timezone identifier below according to
     # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
     environment: [ "TZ=US/Central" ]
-    build: # docker compose build geant4
+    build:
+      # docker compose build geant4
       context: platform/docker
       platforms: [ "linux/amd64" ] # for build time
-  novnc: # X window display sidecar for heprapp and root
+  novnc:
+    # X window display sidecar for heprapp and root
     image: theasp/novnc
     profiles: [ "heprapp" ]
     container_name: noVNC
@@ -22,18 +25,16 @@ services:
       - DISPLAY_HEIGHT=${DISPLAY_HEIGHT:-720}
       - RUN_XTERM=no
     command: >
-      bash -c "mkdir -p ~/.fluxbox &&
-      echo 'session.screen0.toolbar.visible: false' > ~/.fluxbox/init &&
-      echo 'session.styleFile: /usr/share/fluxbox/styles/bora_blue' >> ~/.fluxbox/init &&
-      /app/entrypoint.sh --forever --shared"
-    networks: [ "X11"]
+      bash -c "mkdir -p ~/.fluxbox && echo 'session.screen0.toolbar.visible: false' > ~/.fluxbox/init && echo 'session.styleFile: /usr/share/fluxbox/styles/bora_blue' >> ~/.fluxbox/init && /app/entrypoint.sh --forever --shared"
+    networks: [ "X11" ]
     healthcheck:
-      test: ["CMD-SHELL", "timeout 1s bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8080' || exit 1"]
-      interval: 1s     # check every 1 seconds
-      timeout: 1s      # give up on a single check after 1s
-      retries: 5       # try 5 times before failing
+      test: [ "CMD-SHELL", "timeout 1s bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/8080' || exit 1" ]
+      interval: 1s # check every 1 seconds
+      timeout: 1s # give up on a single check after 1s
+      retries: 5 # try 5 times before failing
       start_period: 0s # wait 0s before the first check
-  heprapp: # docker compose --profile heprapp up
+  heprapp:
+    # docker compose --profile heprapp up
     image: physino/heprapp:latest
     profiles: [ "heprapp" ]
     container_name: HepRApp
@@ -51,16 +52,18 @@ services:
     volumes:
       - ".:/root/geant4"
       - "./vis/HepRepFile/app/user.properties:/user.properties"
-    networks: [ "X11"]
-    build: # docker compose build heprapp
+    networks: [ "X11" ]
+    build:
+      # docker compose build heprapp
       context: vis/HepRepFile/app
       platforms: [ "linux/amd64", "linux/arm64" ]
-  root: # docker compose --profile root up
+  root:
+    # docker compose --profile root up
     command: >
-      bash -c "socat TCP-LISTEN:9001,fork,reuseaddr TCP:127.0.0.1:9375 & 
-      root -l --web=server:9375 -e \"new TBrowser;\""
+      bash -c "socat -d0 TCP-LISTEN:9001,fork,reuseaddr TCP:127.0.0.1:9375 &  root -l --web=server:9375 -e \"new TBrowser;\""
     image: physino/root # https://hub.docker.com/r/physino/root
     profiles: [ "root" ]
+    container_name: ROOT
     ports: [ "9375:9001" ]
     volumes:
       - .:/root/geant4
